### ISSUE TITLE
Handle API timeouts

### ISSUE THREAD

**Issue by Silvan-WMDE** [wmde/wikidata-constraints-violation-checker#22]

**Comment by lydiapintscher** [comment]
@Silvan-WMDE My understanding is this is being handled in your open pull request. Should we link it?

**Comment by Silvan-WMDE** [comment]
yes, for the wbcheckconstraints endpoint, which I think is adressed in this issue, API timeouts are handled in pull request #29. Specifically, if the query for a large batch of items fails, the `checkQualityByBatch()` function will fall back to calling `checkQualityByItem()` for each individual item one-by-one and finally ignore the single item culprit, if it still times out.

The code is included in commit [5752b00](https://github.com/wmde/wikidata-constraints-violation-checker/pull/29/commits/5752b009b47321227c3dc273005886aff8f4b93e)
